stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/nginx-server:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/nginx-server:latest
  tags:
    - qiushaocloud-runner
